---
driver:
  name: vagrant
  customize:
          memory: 1024
          cpus: 1
  log_level: info

provisioner:
  name: chef_zero
  chef_omnibus_url: <%= ENV['CHEF_OMNIBUS_URL'] %>
  require_chef_omnibus: <%= ENV['CHEF_OMNIBUS_VER'] %>
  client_rb:
    #https_proxy: <%= ENV['HTTPS_PROXY'] %>
    #http_proxy: <%= ENV['HTTP_PROXY'] %>
    no_proxy: <%= ENV['NO_PROXY'] %>

platforms:
  -
    driver_config:
      box: <%= ENV['VAGRANT_BOX_NAME'] %>
      box_url: <%= ENV['VAGRANT_BOX_URL'] %>
      require_chef_omnibus: <%= ENV['CHEF_OMNIBUS_VER'] %>
      chef_omnibus_url: <%= ENV['CHEF_OMNIBUS_URL'] %>
    name: <%= ENV['VAGRANT_PLATFORM_NAME'] %>
    driver_plugin: vagrant

suites:
  - name: consul-cluster
    # this is used to setup local consul server for development work
    driver:
      vm_hostname: consul-cluster
      network:
        - ["private_network", {ip: "192.168.237.15"}]
    run_list:
      - recipe[instance_config::consul_server]
    attributes:
      authorization:
        sudo:
          users:
            - kitchen
            - vagrant
      consul:
        bootstrap_expect: 1
        advertise_interface: eth1
        datacenter: vagrant
        servers: [ '192.168.237.15' ]
  - name: consul-client
    driver:
      vm_hostname: consul-client
      network:
      - ["private_network", {ip: "192.168.237.17"}]
    run_list:
      # Uncomment instance_config if using for cookbook_tgtcfg, not required for role cookbooks
      # - recipe[instance_config::default]
      # ADD YOUR RECIPE HERE <<<<<<======
    data_bags_path: <%= ENV['KITCHEN_DATA_BAGS_PATH'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['KITCHEN_ENCRYPTED_DATA_BAG_SECRET_KEY_PATH'] %>
    attributes:
      consul:
        datacenter: vagrant
        advertise_interface: eth1
        client_interface: eth1
        servers: [ '192.168.237.15' ]
